stages:
  - fetch-config
  - build
  - test
  - deploy-dev
  - deploy-prod


fetch-config:
  tags:
    - FrontendadminpanelUATk8
  stage: fetch-config
  script:
    - echo "Fetching API configuration..."
    - curl -s https://configuat.fiaglobal.com/products -o config.json
    - echo "config.json created successfully."
  artifacts:
    name: "config-${CI_COMMIT_REF_NAME}"
    paths:
      - config.json
    expire_in: 1 week
  only:
    - DevRelease
    
build-job:
  tags:
    - FrontendadminpanelUATk8
  stage: build
  script:

    - echo "Hello v1.1, $GITLAB_USER_LOGIN!"
    - echo "Hello System-user, $USER"
    - bash deploy/build-deploy.sh
  only:
    - DevRelease 
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - ${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}.tar.gz
    expire_in: 1 week

fetch-config:
  tags:
    - FrontendadminpanelUATk8
  stage: fetch-config
  script:
    - echo "Fetching API configuration..."
    - curl -s https://configstag.fiaglobal.com/products -o config.json
    - echo "config.json created successfully."
  artifacts:
    name: "config-${CI_COMMIT_REF_NAME}"
    paths:
      - config.json
    expire_in: 1 week
  only:
    - DeveloperStag

build-job-Stag:
  tags:
    - FrontendadminpanelUATk8    
  stage: build
  script:

    - echo "Hello v1.1, $GITLAB_USER_LOGIN!"
    - echo "Hello System-user, $USER"
    - bash deploy/stage-build-deploy.sh
  only:
    - DeveloperStag 
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - ${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}.tar.gz
    expire_in: 1 week


build-job-k8s:
  tags:
   - FrontendadminpanelUATk8
  stage: build
  script:
    - echo "build job"
    - bash deploy/build-image-deploy.sh
  only:
    - DevReleaseK8s    

build-job-prod:
  tags:
   - FrontendadminpanelUATk8
  stage: build
  script:

    - echo "Hello v1.1, $GITLAB_USER_LOGIN!"
    - echo "Hello System-user, $USER"
    - bash deploy/build-proddeploy.sh
  only:
    - ProdRelease 
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - ${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}.tar.gz
    expire_in: 1 week






deploy-job-dev:
  tags:
    - FrontendadminpanelUAT
  stage: deploy-dev
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - bash deploy/deploy.sh
  only:
    - DevRelease 

deploy-job-stag:
  tags:
    - FrontendadminpanelUAT
  stage: deploy-dev
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - bash deploy/stagdeploy.sh
  only:
    - DeveloperStag 

#deploy-job-dev-Stag:
 # tags:
  # - FrontendadminpanelUAT
  #stage: deploy-dev
  #script:
   # - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    #- bash deploy/stagdeploy.sh
  #only:
    #- DeveloperStag


deploy-job-UAT-k8s:
  tags:
   - FrontendadminpanelUATk8
  stage: deploy-dev
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - bash deploy/k8helm-image-deploy.sh
  only:
    - DevReleaseK8s



deploy-job-prod:
  tags:
    - FrontendadminpanelProd
  stage: deploy-prod
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - bash deploy/proddeploy.sh
  only:
    - ProdRelease
